var a = 100;
var b = 200;
console.log(a + b);
console.log(a - b);
console.log(a < b);
console.log(a == b);
console.log(a != b);
a++;
console.log(a);
b--;
console.log(b--);
var num = -2;
var result = num < 0 ? "negative" : "positive";
console.log(result);
